apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tomcattest-deploy-v3
  name: tomcattest-deploy-v3
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcattest
  template:
    metadata:
      labels:
        app: tomcattest
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/xgq-dockerimages/tomcat-test:12
        imagePullPolicy: IfNotPresent
        name: tomcattest-v3
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /usr/local/apache-tomcat-9.0.96/webapps/
          name: tomcat-web
          readOnly: false
      volumes:
      - name: tomcat-web
        hostPath:
          path: /opt/tomcat-web
      imagePullSecrets:
      - name: aliyun-xgq
