apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tomcat-test-version
  name: tomcat-test-version
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcattest
  template:
    metadata:
      labels:
        app: tomcattest
    spec:
      containers:
      - image: tomcat-test-image
        imagePullPolicy: IfNotPresent
        name: tomcat-test-version
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: aliyun-xgq
