apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: tomcattest-deploy-vtomcat-version
  name: tomcattest-deploy-vtomcat-version
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcattest
  template:
    metadata:
      labels:
        app: tomcattest
    spec:
      containers:
      - image: tomcat-test-image
        imagePullPolicy: IfNotPresent
        name: tomcattest-vtomcat-version
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /usr/local/apache-tomcat-9.0.96/webapps/
          name: tomcat-web
          readOnly: false
      volumes:
      - name: tomcat-web
        hostPath:
          path: /opt/tomcat-web
      imagePullSecrets:
      - name: aliyun-xgq
